export type OutlookRegionId = "gulf" | "sudan" | "classical";

export type OutlookTone = "heat" | "humid" | "rain" | "cool" | "transition" | "neutral";

export type MansionOutlook = {
  season: string;
  title: string;
  air: string;
  land: string;
  guidance: string;
  tone: OutlookTone;
};

export type MansionOutlookCopy = Omit<MansionOutlook, "tone">;

const GULF_OUTLOOKS: MansionOutlook[] = [
  {
    season: "Late spring · Al-Thurayya",
    title: "The hot season gathers strength",
    air: "Afternoons become hotter under mostly dry skies; fresh northwesterly winds can lift dust.",
    land: "Evaporation accelerates and exposed soil loses moisture quickly.",
    guidance: "Move strenuous outdoor work toward dawn and check irrigation intervals.",
    tone: "heat",
  },
  {
    season: "Late spring · Al-Thurayya",
    title: "Dry heat becomes established",
    air: "Hot, bright days dominate inland, with occasional dusty wind episodes.",
    land: "Pasture and unshaded ground dry rapidly as water demand rises.",
    guidance: "Secure light materials and protect young plants from wind and heat stress.",
    tone: "heat",
  },
  {
    season: "Early summer · Al-Thurayya",
    title: "Summer heat settles in",
    air: "Very hot afternoons and warm nights become the normal pattern; rain is uncommon.",
    land: "Irrigation demand is high and shallow water sources warm quickly.",
    guidance: "Maintain shade, hydration and early-morning work routines.",
    tone: "heat",
  },
  {
    season: "Early summer · Al-Tuwaibi'",
    title: "Heat intensifies before Al-Jawza'",
    air: "Long, very hot days continue, sometimes accompanied by dry northwesterly winds and dust.",
    land: "Soil moisture loss is severe on exposed ground.",
    guidance: "Inspect cooling, irrigation and livestock water before the peak-heat period.",
    tone: "heat",
  },
  {
    season: "Peak summer · Al-Jawza'",
    title: "Jumrat al-Qayz begins",
    air: "Extreme daytime heat dominates; the interior is often dry while haze or dust may reduce clarity.",
    land: "Water use and evaporation approach seasonal highs.",
    guidance: "Treat midday exposure as a heat risk and schedule field activity at first light.",
    tone: "heat",
  },
  {
    season: "Peak summer · Al-Jawza'",
    title: "Peak heat with rising coastal humidity",
    air: "Very hot days continue. The interior stays drier while Gulf coastal districts can feel humid, with haze or dust at times.",
    land: "Evaporation and water demand are near seasonal highs; warm nights limit overnight cooling.",
    guidance: "Plan exposed work for dawn, protect water supplies and treat this as a heat-risk period.",
    tone: "humid",
  },
  {
    season: "Peak summer · Al-Mirzam",
    title: "Severe heat and warm nights persist",
    air: "Intense heat remains established, with coastal humidity and occasional dusty wind shifts.",
    land: "Plants and animals face sustained thermal and water stress.",
    guidance: "Keep cooling, shade and water systems under close observation.",
    tone: "humid",
  },
  {
    season: "Late summer · Al-Kulaibain",
    title: "Humid heat reaches its oppressive phase",
    air: "Coastal humidity can be very high and nights remain warm; inland locations stay extremely hot.",
    land: "High humidity slows nighttime cooling while evaporation remains strong inland.",
    guidance: "Allow extra recovery time for outdoor crews and watch stored goods for condensation.",
    tone: "humid",
  },
  {
    season: "Suhail",
    title: "The first easing is felt at night",
    air: "Days remain very hot, but dawn and nighttime conditions may begin a slow improvement; humidity can persist.",
    land: "Heat stress remains high even as the seasonal turn begins.",
    guidance: "Do not mistake cooler dawns for the end of summer heat.",
    tone: "transition",
  },
  {
    season: "Suhail · Al-Jabha",
    title: "Hot days, gradually milder nights",
    air: "Daytime heat continues while nights slowly moderate; humid or hazy coastal spells remain possible.",
    land: "Dew and humidity become more noticeable in some coastal and low-lying areas.",
    guidance: "Continue heat precautions while preparing for the autumn transition.",
    tone: "transition",
  },
  {
    season: "Suhail",
    title: "Heat begins a slow retreat",
    air: "Afternoons are still hot, but nighttime temperatures trend downward and visibility often improves.",
    land: "Water demand remains substantial, though overnight losses begin to ease.",
    guidance: "Use the improving mornings for maintenance and field preparation.",
    tone: "transition",
  },
  {
    season: "Suhail · Al-Sarfah",
    title: "The summer pattern turns away",
    air: "Nights become more comfortable and the most persistent summer heat starts to weaken.",
    land: "Cooling ground temperatures support preparation for the coming rain-marker season.",
    guidance: "Inspect drainage and exposed roofs before the more changeable autumn period.",
    tone: "transition",
  },
  {
    season: "Al-Wasm",
    title: "Traditional rain-marker season opens",
    air: "Milder mornings arrive, with a greater chance of cloud build-up and isolated showers than in summer.",
    land: "Early rain can revive desert plants and soften dry ground unevenly.",
    guidance: "Watch local forecasts before wadi travel; rainfall remains highly localized.",
    tone: "rain",
  },
  {
    season: "Al-Wasm",
    title: "More changeable skies",
    air: "Pleasant temperatures and occasional cloudy, unstable or showery intervals become more plausible.",
    land: "Where rain falls, germination and surface runoff can begin quickly.",
    guidance: "Keep drainage paths clear and use rainfall observations to guide planting.",
    tone: "rain",
  },
  {
    season: "Al-Wasm",
    title: "Cooler nights with rain opportunities",
    air: "Nights cool further; fog, dew or isolated rain may occur under suitable local conditions.",
    land: "Moist pockets can support seasonal vegetation while dry areas remain dusty.",
    guidance: "Base grazing and planting decisions on measured local rainfall, not the calendar alone.",
    tone: "rain",
  },
  {
    season: "Late Al-Wasm",
    title: "The cool season approaches",
    air: "Mornings become distinctly cooler, with occasional fog, cloud or fresh winds.",
    land: "Soil retains moisture longer where seasonal rain has occurred.",
    guidance: "Prepare cold-sensitive plants and livestock for sharper night cooling.",
    tone: "cool",
  },
  {
    season: "Al-Murabba'aniyah",
    title: "Winter opens with cold nights",
    air: "Cool days and colder nights establish themselves; fresh wind can make conditions feel colder.",
    land: "Dew is more persistent and sheltered low areas cool rapidly overnight.",
    guidance: "Protect sensitive crops, animals and outdoor plumbing from cold exposure.",
    tone: "cool",
  },
  {
    season: "Al-Murabba'aniyah",
    title: "Cold deepens",
    air: "Nighttime cold strengthens, with occasional windy or unsettled spells.",
    land: "Slow evaporation helps retain soil moisture but cold can limit growth.",
    guidance: "Use wind protection and avoid over-irrigating cold, slow-drying soil.",
    tone: "cool",
  },
  {
    season: "Al-Murabba'aniyah",
    title: "Traditional coldest phase",
    air: "The cycle favours the coldest nights and crisp mornings of the regional winter.",
    land: "Frost is uncommon on the coast but can occur in colder inland and elevated pockets.",
    guidance: "Monitor official temperature warnings for farms in exposed inland areas.",
    tone: "cool",
  },
  {
    season: "Al-Shabat",
    title: "Cold, dry winds can sharpen",
    air: "Fresh to strong winds may bring a penetrating chill and occasional blowing dust.",
    land: "Wind dries exposed surfaces even while temperatures remain low.",
    guidance: "Secure loose equipment and protect seedlings from cold wind.",
    tone: "cool",
  },
  {
    season: "Al-Shabat",
    title: "Winter begins to fluctuate",
    air: "Cold nights alternate with noticeably milder afternoons; fog or wind may occur.",
    land: "Plant growth slowly responds to longer, warmer days.",
    guidance: "Keep cold protection available despite temporary warm spells.",
    tone: "transition",
  },
  {
    season: "Al-Aqarib",
    title: "Late cold remains possible",
    air: "Rapid changes between mild days, cool nights, wind and isolated showers are traditional markers.",
    land: "Variable temperature and moisture can stress new growth.",
    guidance: "Delay removing winter protection until local conditions are consistently mild.",
    tone: "transition",
  },
  {
    season: "Al-Aqarib",
    title: "Spring warmth advances",
    air: "Warmer afternoons become frequent, though passing cloud, wind or a late cool spell can interrupt them.",
    land: "Seasonal vegetation and flowering respond quickly where soil moisture is available.",
    guidance: "Inspect for pests and adjust irrigation as growth accelerates.",
    tone: "transition",
  },
  {
    season: "Early spring",
    title: "Mild weather and active growth",
    air: "Generally mild days and comfortable nights favour outdoor work; occasional dust or showers remain possible.",
    land: "Growth and flowering are active where winter moisture persists.",
    guidance: "Use the mild window for planting, maintenance and field work.",
    tone: "transition",
  },
  {
    season: "Al-Hamimain",
    title: "Spring turns warmer",
    air: "Daytime warmth increases and dry, dusty wind episodes become more likely.",
    land: "Soils begin drying faster as sunlight and temperature rise.",
    guidance: "Increase water checks gradually and protect tender growth from wind.",
    tone: "heat",
  },
  {
    season: "Al-Hamimain",
    title: "Warm days become dominant",
    air: "Warm to hot afternoons prevail, with occasional haze, dust or local spring instability.",
    land: "Moisture demand rises and exposed vegetation begins to dry.",
    guidance: "Prepare cooling and irrigation systems before sustained heat arrives.",
    tone: "heat",
  },
  {
    season: "Al-Dhira'ain",
    title: "Heat builds rapidly",
    air: "Hotter days and dusty winds signal the approach of the Gulf summer.",
    land: "Evaporation accelerates and surface water warms.",
    guidance: "Complete heat-season maintenance and review outdoor work hours.",
    tone: "heat",
  },
  {
    season: "Al-Dhira'ain",
    title: "Late-spring heat closes the cycle",
    air: "Hot, mainly dry conditions dominate before Al-Sharatain renews the cycle.",
    land: "Dry ground and vegetation become increasingly heat stressed.",
    guidance: "Enter the new cycle with shade, water and dust plans ready.",
    tone: "heat",
  },
];

const SUDAN_OUTLOOKS: MansionOutlook[] = [
  {
    season: "Hot dry season",
    title: "Severe pre-kharif heat",
    air: "Very hot afternoons, dry air and dust dominate much of Sudan; local conditions vary strongly north to south.",
    land: "Water stress is high and rain-fed soil remains hard and dry.",
    guidance: "Protect water supplies and schedule land preparation outside peak heat.",
    tone: "heat",
  },
  {
    season: "Pre-kharif transition",
    title: "Heat with isolated storm signals",
    air: "Intense heat continues while isolated cloud build-up or early storms may appear farther south.",
    land: "Most northern ground remains dry; southern fields may receive uneven first wetting.",
    guidance: "Prepare seed and drainage, but do not treat one storm as a settled rainy season.",
    tone: "transition",
  },
  {
    season: "Pre-kharif transition",
    title: "Rain build-up begins",
    air: "Humidity and thunderstorm potential gradually increase from the south and southeast.",
    land: "First useful rainfall may soften fields unevenly and begin pasture recovery.",
    guidance: "Use measured soil moisture—not the calendar alone—to decide when to sow.",
    tone: "rain",
  },
  {
    season: "Kharif onset",
    title: "First planting rains become more likely",
    air: "Storms and haboob outflows become more frequent across rain-fed central and southern zones.",
    land: "Early runoff, soil wetting and germination begin where rainfall is sufficient.",
    guidance: "Start planting only after locally adequate, follow-up rainfall is established.",
    tone: "rain",
  },
  {
    season: "Early kharif",
    title: "Planting window opens",
    air: "Rainfall becomes more regular in many agricultural zones, though distribution remains uneven.",
    land: "Soil moisture supports sowing and emergence; erosion can start on bare slopes.",
    guidance: "Protect seedbeds from runoff and monitor gaps in germination.",
    tone: "rain",
  },
  {
    season: "Early kharif",
    title: "Crop establishment under active storms",
    air: "Thunderstorms, gust fronts and dust walls can precede useful rain.",
    land: "Young sorghum, millet and pasture establish where rainfall has been sustained.",
    guidance: "Replant failed patches only after checking the near-term local forecast.",
    tone: "rain",
  },
  {
    season: "Active kharif",
    title: "Sustained rain and rapid field growth",
    air: "More frequent showers and thunderstorms bring cooler breaks between humid, warm periods.",
    land: "Crop growth accelerates; runoff, waterlogging and weed pressure rise in wetter districts.",
    guidance: "Maintain drainage, control weeds early and avoid flooded crossings.",
    tone: "rain",
  },
  {
    season: "Active kharif",
    title: "Rainfall intensifies in many farming zones",
    air: "Cloudier spells and repeated storms become characteristic, with strong local variation.",
    land: "Soil moisture is generally favourable, but saturated plots can suffer nutrient loss.",
    guidance: "Inspect bunds and drainage after every heavy storm.",
    tone: "rain",
  },
  {
    season: "Peak kharif",
    title: "High-rainfall and flood-risk phase",
    air: "Heavy local downpours and storm outflows are traditional risks during the core rainy period.",
    land: "Wadis, low fields and river-adjacent areas may flood; crops enter vigorous growth.",
    guidance: "Follow official flood alerts and keep livestock away from drainage channels.",
    tone: "rain",
  },
  {
    season: "Peak kharif · Al-Jabha",
    title: "Fourteen-day core of the rainy season",
    air: "Repeated storms and heavy rainfall are traditional markers, although totals differ widely across Sudan.",
    land: "Flooding, waterlogging and crop damage can accompany otherwise beneficial rain.",
    guidance: "Prioritize drainage and official river or flash-flood warnings.",
    tone: "rain",
  },
  {
    season: "Peak kharif",
    title: "Wet soils and established crops",
    air: "Frequent rain may continue, with humid conditions between storms.",
    land: "Fields can remain saturated; weeds, pests and crop disease pressure increase.",
    guidance: "Scout crops and time field access to avoid compacting wet soil.",
    tone: "rain",
  },
  {
    season: "Late kharif",
    title: "Rain begins a gradual retreat",
    air: "Storm frequency starts easing in some areas, though heavy late events remain possible.",
    land: "Standing crops still depend on useful finishing rain; saturated ground begins to drain.",
    guidance: "Keep drainage open and monitor crop maturity before reducing field attention.",
    tone: "rain",
  },
  {
    season: "Late kharif",
    title: "Last useful rains and maturing crops",
    air: "Longer dry breaks appear between increasingly isolated storms.",
    land: "Crops mature and pasture remains green where the season was favourable.",
    guidance: "Prepare harvest storage while protecting mature crops from late storms.",
    tone: "transition",
  },
  {
    season: "Darat transition",
    title: "Drying conditions return",
    air: "Skies clear more often and humidity falls as the rainy season withdraws.",
    land: "Fields dry, roads improve and harvest preparation accelerates.",
    guidance: "Use dry intervals for harvest, transport and storage preparation.",
    tone: "transition",
  },
  {
    season: "Harvest season",
    title: "Clearer skies favour harvest",
    air: "Dry weather becomes dominant, with cooler nights developing gradually.",
    land: "Sorghum and millet harvesting expands across rain-fed areas.",
    guidance: "Dry grain thoroughly and protect stores from residual moisture and pests.",
    tone: "transition",
  },
  {
    season: "Harvest season",
    title: "Dry, cooling conditions",
    air: "Days remain warm while mornings and nights become noticeably cooler.",
    land: "Harvest and transport conditions are generally favourable.",
    guidance: "Ventilate grain stores and monitor post-harvest losses.",
    tone: "cool",
  },
  {
    season: "Sudanese winter",
    title: "Cool mornings and dry air",
    air: "A dry northerly pattern brings cooler mornings, especially inland and northward.",
    land: "Rain-fed fields dry out; irrigated winter cultivation becomes more important.",
    guidance: "Adjust irrigation to lower evaporation and protect sensitive seedlings at night.",
    tone: "cool",
  },
  {
    season: "Sudanese winter",
    title: "Cold nights strengthen",
    air: "Dry, clear nights allow rapid cooling, while afternoons remain comfortable to warm.",
    land: "Dew can occur locally, but most land remains dry without irrigation.",
    guidance: "Protect cold-sensitive vegetables and livestock in exposed areas.",
    tone: "cool",
  },
  {
    season: "Sudanese winter",
    title: "Cool, stable and dry",
    air: "Mostly clear skies and cool nights dominate; dusty northerly winds can occur.",
    land: "Winter crops rely on irrigation and careful water scheduling.",
    guidance: "Use cooler conditions for maintenance and controlled irrigation.",
    tone: "cool",
  },
  {
    season: "Coldest phase",
    title: "The cycle's coolest nights",
    air: "Night and dawn temperatures reach their seasonal low in many inland areas.",
    land: "Growth slows for heat-loving plants, while cool-season crops benefit.",
    guidance: "Monitor temperature-sensitive crops and young animals before dawn.",
    tone: "cool",
  },
  {
    season: "Late winter",
    title: "Cool nights, warmer afternoons",
    air: "The daily temperature range widens as afternoons warm but nights remain cool.",
    land: "Irrigated crops begin responding to longer, warmer days.",
    guidance: "Increase irrigation only as measured soil moisture requires.",
    tone: "transition",
  },
  {
    season: "Hot-season approach",
    title: "Dry warmth returns",
    air: "Afternoon temperatures rise and dry winds become more noticeable.",
    land: "Surface soil dries faster and water demand starts increasing.",
    guidance: "Service pumps and water systems before the main hot season.",
    tone: "heat",
  },
  {
    season: "Hot dry season",
    title: "Heat and dust increase",
    air: "Hot, dry days and dusty northerly or variable winds become common.",
    land: "Unirrigated vegetation cures rapidly and water stress grows.",
    guidance: "Protect stored produce and machinery from dust ingress.",
    tone: "heat",
  },
  {
    season: "Hot dry season",
    title: "Strong daytime heating",
    air: "Very hot afternoons establish across much of the country under mostly dry skies.",
    land: "Irrigated agriculture faces increasing evaporative demand.",
    guidance: "Water efficiently at cooler hours and reduce midday labour exposure.",
    tone: "heat",
  },
  {
    season: "Hot dry season",
    title: "Water stress intensifies",
    air: "Persistent heat and occasional dust or haze dominate.",
    land: "Pasture, soil and open water lose moisture rapidly.",
    guidance: "Prioritize reliable drinking water for people and livestock.",
    tone: "heat",
  },
  {
    season: "Severe hot season",
    title: "Extreme heat develops",
    air: "The hottest seasonal pattern expands, with very warm nights in some areas.",
    land: "Heat stress can damage crops and reduce livestock productivity.",
    guidance: "Use shade, ventilation and dawn work schedules.",
    tone: "heat",
  },
  {
    season: "Severe hot season",
    title: "Dust, heat and haboob preparation",
    air: "Extreme heating continues; unstable wind shifts may precede the first southern storms.",
    land: "Dry, bare ground is highly vulnerable to wind erosion.",
    guidance: "Secure roofs, covers and equipment before strong outflow winds.",
    tone: "heat",
  },
  {
    season: "Pre-kharif threshold",
    title: "Hottest period before the cycle renews",
    air: "Severe heat persists while humidity and isolated storm signals slowly begin returning from the south.",
    land: "Water scarcity remains critical before dependable rainfall arrives.",
    guidance: "Prepare fields and drainage, but wait for locally sufficient rain before sowing.",
    tone: "transition",
  },
];

const CLASSICAL_OUTLOOKS: MansionOutlook[] = Array.from({ length: 28 }, () => ({
  season: "Classical reference profile",
  title: "Regional weather profile not yet selected",
  air: "The classical mansion position is shown without inferring local heat, rain or wind outside a configured region.",
  land: "Seasonal conditions can differ greatly with latitude, elevation, coast and terrain.",
  guidance: "Use regional location or choose a supported tradition for a locally meaningful seasonal outlook.",
  tone: "neutral",
}));

export const OUTLOOKS: Record<OutlookRegionId, MansionOutlook[]> = {
  gulf: GULF_OUTLOOKS,
  sudan: SUDAN_OUTLOOKS,
  classical: CLASSICAL_OUTLOOKS,
};

export const OUTLOOK_ICONS: Record<OutlookTone, string> = {
  heat: "☀",
  humid: "≈",
  rain: "☂",
  cool: "✦",
  transition: "◐",
  neutral: "⌖",
};
